/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.piedrapapeltijera;

import Clases.Juego;
import Clases.Mano;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author mauri
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());
    private Juego juego;
    private int partidasGanadasJ1 = 0;
    private int partidasGanadasJ2 = 0;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
        this.juego = new Juego();
        
        buttonGroup1.add(piedra1);
        buttonGroup1.add(papel1);
        buttonGroup1.add(tijera1);
        
        buttonGroup2.add(piedra2);
        buttonGroup2.add(papel2);
        buttonGroup2.add(tijera2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        piedra1 = new javax.swing.JRadioButton();
        piedra2 = new javax.swing.JRadioButton();
        papel2 = new javax.swing.JRadioButton();
        papel1 = new javax.swing.JRadioButton();
        tijera1 = new javax.swing.JRadioButton();
        tijera2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonJugar = new javax.swing.JToggleButton();
        txtj1 = new javax.swing.JTextField();
        txtj2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        piedra1.setSelected(true);
        piedra1.setText("1");

        papel1.setText("2");

        tijera1.setText("3");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ppt_piedra.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ppt_piedra.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ppt_papel.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ppt_papel.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ppt_tijera.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ppt_tijera.jpg"))); // NOI18N

        jLabel1.setText("Jugador 1");

        jLabel2.setText("Jugador 2");

        botonJugar.setText("Jugar");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        jLabel5.setText("Partidas ganadas j1");

        jLabel10.setText("Partidas ganadas j2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(piedra1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(papel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(tijera1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtj2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtj1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tijera2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(papel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(piedra2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(piedra1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtj2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(botonJugar))
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(papel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(tijera1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(123, 123, 123)
                .addComponent(piedra2)
                .addGap(189, 189, 189)
                .addComponent(papel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tijera2)
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
       
        
        
        boolean seleccionado = false;
        
        JRadioButton [] botones = {piedra1,papel1,tijera1};
        for (int i = 0; i <botones.length; i++) {
            if(botones[i].isSelected()){
                seleccionado = true;
            }
        }
        
        if(!seleccionado){
            JOptionPane.showMessageDialog(null, "Selecciona tu mano pls");
        } else {
            Mano manoj1=null , manoj2=null;
            
            if(this.piedra1.isSelected()){
                manoj1 = Mano.PIEDRA;
                System.out.println("Mano seleccionada j1 : 0");
            }
            if(this.papel1.isSelected()){
                manoj1 = Mano.PAPEL;
                System.out.println("Mano seleccionada j1 : 1");
            }
            if(this.tijera1.isSelected()){
                manoj1 = Mano.TIJERA;
                System.out.println("Mano seleccionada j1 : 2");
            }

            
            int manoAleatoria = generarNumeroAlzar(0, 2);
            System.out.println("Mano jugador 2:"+manoAleatoria);
            switch (manoAleatoria){
                case 0:
                    piedra2.setSelected(true);
                    manoj2 = Mano.PIEDRA;
                    break;
                case 1:
                    papel2.setSelected(true);
                    manoj2 = Mano.PAPEL;
                    break;
                case 2:
                    tijera2.setSelected(true);
                    manoj2 = Mano.TIJERA;
                    break;
            }
            
            System.out.println("J1: "+manoj1.toString()+"J2: "+manoj2.toString());
            
            int resultado = this.juego.ganador(manoj1, manoj2);
            System.out.println(resultado);
            
            switch (resultado) {
                case -1:
                    JOptionPane.showMessageDialog(null, "Ganador:\nJugador 2");
                    this.partidasGanadasJ2++;
                    txtj2.setText(partidasGanadasJ2+"");
                    break;
                case 0:
                    JOptionPane.showMessageDialog(null, "Empate nadie puntua");
                    break;
                case 1:
                    JOptionPane.showMessageDialog(null, "Ganador:\nJugador 1");
                    this.partidasGanadasJ1++;
                    txtj1.setText(partidasGanadasJ1+"");
                    break;
                default:
                    throw new AssertionError();
            }
            
            
           
        }
        
        
    }//GEN-LAST:event_botonJugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonJugar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton papel1;
    private javax.swing.JRadioButton papel2;
    private javax.swing.JRadioButton piedra1;
    private javax.swing.JRadioButton piedra2;
    private javax.swing.JRadioButton tijera1;
    private javax.swing.JRadioButton tijera2;
    private javax.swing.JTextField txtj1;
    private javax.swing.JTextField txtj2;
    // End of variables declaration//GEN-END:variables

public static int generarNumeroAlzar(int min, int max) {
        if (min == max) {
            return min; // único valor posible
        }
        // Si están al revés, intercambiamos
        if (min > max) {
            int tmp = min;
            min = max;
            max = tmp;
        }
        // Usamos long para evitar overflow al calcular el tamaño del rango
        long rango = (long) max - (long) min + 1L; // tamaño del rango inclusivo
        if (rango <= 0L) {
            // Esto solo pasaría si el cálculo sobrepasa los límites de int (extremadamente improbable aquí)
            throw new IllegalArgumentException("Rango inválido: demasiado grande");
        }
        // Math.random() devuelve [0.0,1.0). Multiplicando por rango obtenemos [0, rango)
        long offset = (long) (Math.random() * rango); // offset dentro del rango
        return (int) (min + offset);
    }

}
