/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import CapaLogica.GestorArchivos;
import capaDatos.Nota;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author mauricio
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(PantallaPrincipal.class.getName());
    private GestorArchivos gestor;
    private String rutaCarpetaNotas;
    private DefaultListModel<String> modeloLista;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        // Inicializar el gestor de archivos
        rutaCarpetaNotas = System.getProperty("user.home") + File.separator + "Notas";
        gestor = new GestorArchivos(rutaCarpetaNotas);

        initComponents();

        // Configurar el modelo de la lista
        modeloLista = new DefaultListModel<>();
        listaNotas.setModel(modeloLista);

        // Cargar las notas existentes
        cargarNotas();

        // Agregar listener a la lista para mostrar el contenido de la nota seleccionada
        listaNotas.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && listaNotas.getSelectedIndex() != -1) {
                mostrarNotaSeleccionada();
            }
        });

        // Actualizar la fecha actual
        actualizarFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaNotas = new javax.swing.JList<>();
        btnNuevaNota = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        txtFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 7, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setViewportView(listaNotas);

        btnNuevaNota.setBackground(new java.awt.Color(0, 153, 255));
        btnNuevaNota.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnNuevaNota.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaNota.setText("+Nueva nota");
        btnNuevaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnNuevaNota, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNuevaNota, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(29, Short.MAX_VALUE)));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 650));

        jPanel3.setBackground(new java.awt.Color(0, 7, 79));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Diario v1");

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336,
                                        Short.MAX_VALUE)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 285,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addGap(47, 47, 47)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnBuscar)))
                                .addContainerGap(12, Short.MAX_VALUE)));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 60));

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane2.setViewportView(areaTexto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 610, 490));

        jTextField1.setBackground(new java.awt.Color(0, 7, 61));
        jTextField1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Predeterminado");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 340, 40));

        btnGuardar.setBackground(new java.awt.Color(0, 153, 255));
        btnGuardar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 610, 53));

        txtFecha.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setText("Fecha");
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed
        String titulo = jTextField1.getText().trim();
        String contenido = areaTexto.getText().trim();

        if (titulo.isEmpty() || titulo.equals("Predeterminado")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor ingresa un título para la nota",
                    "Título requerido",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (gestor.guardar(titulo, contenido)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Nota guardada correctamente",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Limpiar los campos
            jTextField1.setText("Predeterminado");
            areaTexto.setText("");

            // Recargar la lista de notas
            cargarNotas();

            // Actualizar la fecha
            actualizarFecha();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al guardar la nota",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevaNotaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNuevaNotaActionPerformed
        jTextField1.setText("Predeterminado");
        areaTexto.setText("");
        listaNotas.clearSelection();
        jTextField1.requestFocus();
        actualizarFecha();
    }// GEN-LAST:event_btnNuevaNotaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
        String termino = txtBuscar.getText().trim();

        if (termino.isEmpty()) {
            cargarNotas();
            return;
        }

        List<Nota> resultados = gestor.buscarBinaria(termino);
        modeloLista.clear();

        if (resultados.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encontraron notas con ese título",
                    "Sin resultados",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            cargarNotas();
        } else {
            for (Nota nota : resultados) {
                modeloLista.addElement(nota.toString());
            }
        }
    }// GEN-LAST:event_btnBuscarActionPerformed

    /**
     * Carga todas las notas en la lista
     */
    private void cargarNotas() {
        modeloLista.clear();
        List<Nota> notas = gestor.listar();

        for (Nota nota : notas) {
            modeloLista.addElement(nota.toString());
        }

        txtBuscar.setText("");
    }

    /**
     * Muestra el contenido de la nota seleccionada en el área de texto
     */
    private void mostrarNotaSeleccionada() {
        int indice = listaNotas.getSelectedIndex();
        if (indice >= 0) {
            String itemSeleccionado = modeloLista.get(indice);

            // Buscar la nota completa
            List<Nota> notas = gestor.listar();
            for (Nota nota : notas) {
                if (nota.toString().equals(itemSeleccionado)) {
                    Nota notaCompleta = gestor.leer(nota.getNombreArchivo());
                    if (notaCompleta != null) {
                        jTextField1.setText(notaCompleta.getTitulo());
                        areaTexto.setText(notaCompleta.getContenido());
                        // Mostrar la fecha guardada en la nota
                        if (notaCompleta.getFecha() != null && !notaCompleta.getFecha().isEmpty()) {
                            txtFecha.setText(notaCompleta.getFecha());
                        } else {
                            actualizarFecha();
                        }
                    }
                    break;
                }
            }
        }
    }

    /**
     * Actualiza la etiqueta de fecha con la fecha actual
     */
    private void actualizarFecha() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        txtFecha.setText(sdf.format(new Date()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevaNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> listaNotas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JLabel txtFecha;
    // End of variables declaration//GEN-END:variables
}
