package CapaPresentacion;

import CapaLogica.clsUsuario;
import CapaLogica.metodosSueltos;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author mauricio
 */
public class frLogin extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frLogin.class.getName());
    private boolean selogeo = false;

    /**
     * Creates new form NewJDialog
     */
    public frLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarLogo();
        captchaAlea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsr = new javax.swing.JTextField();
        txtPsw = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtCatcha = new javax.swing.JLabel();
        btncambiar = new javax.swing.JButton();
        confirmcaptcha = new javax.swing.JTextField();
        txtLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Fira Sans Book", 3, 18)); // NOI18N
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Fira Sans Book", 3, 18)); // NOI18N
        jLabel2.setText("Contraseña");

        txtPsw.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnIniciar.setBackground(new java.awt.Color(204, 255, 204));
        btnIniciar.setText("Iniciar sesion");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        btnIniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnIniciarKeyPressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 204, 204));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtCatcha.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N

        btncambiar.setText("Cambiar");
        btncambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPsw, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtCatcha, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btncambiar))
                            .addComponent(confirmcaptcha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(txtLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCatcha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncambiar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmcaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnSalir))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        inicioSecion();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btncambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncambiarActionPerformed
        captchaAlea();
    }//GEN-LAST:event_btncambiarActionPerformed

    private void btnIniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIniciarKeyPressed

    }//GEN-LAST:event_btnIniciarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btncambiar;
    private javax.swing.JTextField confirmcaptcha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtCatcha;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JPasswordField txtPsw;
    private javax.swing.JTextField txtUsr;
    // End of variables declaration//GEN-END:variables

    public void captchaAlea() {
        txtCatcha.setText("" + metodosSueltos.generarNumero(0, 9) + metodosSueltos.generarNumero(0, 9) + metodosSueltos.generarNumero(0, 9) + metodosSueltos.generarNumero(0, 9) + metodosSueltos.generarNumero(0, 9));
    }

    public boolean confirmarCaptcha() {
        if (txtCatcha.getText().equals(confirmcaptcha.getText())) {
            return true;
        } else {
            return false;
        }
    }

    public boolean inicioSecion() {
        clsUsuario usr = new clsUsuario();
        usr.setUsuario(txtUsr.getText());
        usr.setClave(new String(txtPsw.getPassword()));

        boolean credencialesOk = usr.iniciarSession();
        boolean captchaOk = confirmarCaptcha();

        if (credencialesOk && captchaOk) {
            selogeo = true;
            dispose(); // cerrar el diálogo al iniciar sesión correctamente
            return true;
        } else {
            selogeo = false;
            StringBuilder msg = new StringBuilder();
            if (!credencialesOk) {
                msg.append("Usuario o contraseña incorrectos.\n");
            }
            if (!captchaOk) {
                msg.append("Captcha incorrecto.");
            }
            if (msg.length() == 0) {
                msg.append("Error al iniciar sesión.");
            }
            JOptionPane.showMessageDialog(this, msg.toString(), "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            // refrescar captcha y limpiar campos sensibles
            captchaAlea();
            confirmcaptcha.setText("");
            txtPsw.setText("");
            return false;
        }
    }

    public boolean selogeo() {
        return selogeo;
    }

    private void cargarLogo() {

        try {
            // 1. En caso la imagen este en la ruta correcta
            ImageIcon logo = new ImageIcon(getClass().getResource(("/img/isotipo_unprg.png")));

            // Redimensionar
            java.awt.Image img = logo.getImage();
            java.awt.Image imgEscalada = img.getScaledInstance(300, 91, java.awt.Image.SCALE_SMOOTH);
            ImageIcon logoEscalado = new ImageIcon(imgEscalada);
            txtLogo.setIcon(logoEscalado);

            // Centrar la imagen
            txtLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        } catch (Exception e) {

            // 2. En caso no encuentre la imagen
            txtLogo.setText("UNPRG");
            txtLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }
    }

}
