/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package CapaPresentacion;

import CapaLogica.clsProducto;
import capaDatos.clsProductoDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mauricio
 */
public class jdAniadirProductos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdAniadirProductos.class.getName());
    
    // Variables para almacenar el producto seleccionado
    private String prod = "";
    private int cant = 0;
    private int desc = 0;

    /**
     * Creates new form jdAniadirProductos
     */
    public jdAniadirProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTabla();
    }
    
    // Getters para pasar la información al formulario padre
    public String getProd() {
        return prod;
    }

    public void setProd(String prod) {
        this.prod = prod;
    }

    public int getCant() {
        return cant;
    }

    public void setCant(int cant) {
        this.cant = cant;
    }

    public int getDesc() {
        return desc;
    }

    public void setDesc(int desc) {
        this.desc = desc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnomProd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtnomProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomProdKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "nombre", "descripcion", "precio", "stock", "categoria", "marca", "estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnomProd)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtnomProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         if (evt.getClickCount() == 2) {
            int fila = jTable1.getSelectedRow();

            if (fila < 0) {
                JOptionPane.showMessageDialog(this, "Selecciona una fila");
                return;
            }

            // Obtener el código del producto de la tabla (es String)
            String cod = String.valueOf(jTable1.getValueAt(fila, 0));
            
            // Solicitar cantidad
            String ctdStr = String.valueOf(JOptionPane.showInputDialog(this, "Ingrese la cantidad: "));
            
            if (ctdStr != null && !ctdStr.equals("null") && !ctdStr.isEmpty()) {
                try {
                    int ctd = Integer.parseInt(ctdStr);
                    pasarDatos(cod, ctd);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Cantidad no válida");
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void pasarDatos(String cod, int ctd) {
        try {
            clsProducto objPro = clsProductoDao.buscarPorCodigo(cod);
            if (objPro != null) {
                int stock = objPro.getStock();
                if (ctd <= stock) {
                    prod = cod;
                    cant = ctd;
                    String descuento = String.valueOf(JOptionPane.showInputDialog(this,
                            "Ingrese el porcentaje de descuento: ", "0"));
                    
                    try {
                        if (descuento != null && !descuento.equals("null") && !descuento.isEmpty()) {
                            desc = Integer.parseInt(descuento);
                        }
                    } catch (NumberFormatException e) {
                        desc = 0;
                    }
                    
                    // Cerrar el diálogo después de seleccionar
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Stock insuficiente. Stock disponible: " + stock);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Producto no encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void txtnomProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomProdKeyPressed

    }//GEN-LAST:event_txtnomProdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                jdAniadirProductos dialog = new jdAniadirProductos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtnomProd;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
 clsProducto[] c = clsProductoDao.obtener();
        if (c != null) {
            for (int i = 0; i < clsProductoDao.getCantidad(); i++) {
                if (c[i] != null) {
                    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                    modelo.addRow(new Object[] { c[i].getCodigo(), c[i].getNombre(),
                            c[i].getDescripcion(), c[i].getPrecio(), c[i].getStock(), c[i].getCategoria(),
                            c[i].getMarca(), c[i].isEstado() });
                }
            }
        }
    }


}
