/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package CapaPresentacion;

import CapaLogica.clsVenta;
import CapaLogica.clsCliente;
import CapaLogica.clsProducto;
import capaDatos.clsVentaDao;
import capaDatos.clsClienteDao;
import capaDatos.clsProductoDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author mauricio
 */
public class jdVenta extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdVenta.class.getName());

    // Variables para almacenar producto seleccionado
    private String codigoProductoSeleccionado = "";
    private double precioProductoSeleccionado = 0.0;

    /**
     * Creates new form jdVenta
     */
    public jdVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonGroup1.add(radioBoleta);
        buttonGroup1.add(radioFactura);
        cargarVentasEnTabla(); // Cargar ventas existentes al abrir el formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateVenta = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        numVenta = new javax.swing.JTextPane();
        btnBuscarVenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDni = new javax.swing.JTextPane();
        btnBucarCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNomCliente = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        radioBoleta = new javax.swing.JRadioButton();
        radioFactura = new javax.swing.JRadioButton();
        comboTipoCliente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtNomProducto = new javax.swing.JTextPane();
        spinnerCantProd = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescuento = new javax.swing.JTextPane();
        btnAgregarProducto = new javax.swing.JButton();
        btnQuitarProducto = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtSubtotal = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtIGV = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setText("Fecha");

        jLabel2.setText("numero");

        jScrollPane1.setViewportView(numVenta);

        btnBuscarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar1.png"))); // NOI18N
        btnBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(dateVenta, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(btnBuscarVenta)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnBuscarVenta)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(dateVenta, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addContainerGap(36, Short.MAX_VALUE)));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setText("DNI/RUC");

        jScrollPane2.setViewportView(txtDni);

        btnBucarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscarCliente.png"))); // NOI18N
        btnBucarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBucarClienteActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(txtNomCliente);

        jScrollPane4.setViewportView(txtDireccion);

        jLabel4.setText("Tipo Cliente");

        radioBoleta.setText("Boleta");
        radioBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoletaActionPerformed(evt);
            }
        });

        radioFactura.setText("Factura");

        comboTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "RUC" }));

        jLabel5.setText("Cliente");

        jLabel6.setText("Direccion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBucarCliente))
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 303,
                                                        Short.MAX_VALUE)
                                                .addComponent(jScrollPane4)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(radioBoleta)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel4)
                                                        .addGap(35, 35, 35)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radioFactura)
                                        .addComponent(comboTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnBucarCliente)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel4)
                                                .addComponent(comboTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(radioBoleta)
                                                        .addComponent(radioFactura)))
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addContainerGap(36, Short.MAX_VALUE)));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setText("Producto");

        jScrollPane5.setViewportView(txtNomProducto);

        jLabel8.setText("Cantidad");

        jLabel9.setText("Descuento");

        jScrollPane6.setViewportView(txtDescuento);

        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/agregar.png"))); // NOI18N
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnQuitarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/quitar.png"))); // NOI18N
        btnQuitarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 295,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(spinnerCantProd, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 149,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnQuitarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addGroup(jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnAgregarProducto)
                                                .addComponent(btnQuitarProducto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8)
                                                .addComponent(spinnerCantProd, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9))
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)));

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Código", "Nombre", "Precio", "Cantidad", "Descuento", "Nuevo Precio", "SubTotal"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tablaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVentaMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tablaVenta);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Subtotal");

        jLabel11.setText("IGV");

        jLabel12.setText("Total");

        jScrollPane8.setViewportView(txtSubtotal);

        jScrollPane9.setViewportView(txtIGV);

        jScrollPane10.setViewportView(jTextPane9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 82,
                                                Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 82,
                                                        Short.MAX_VALUE)
                                                .addComponent(jScrollPane8)))
                                .addGap(25, 25, 25)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/limpiarMarca.png"))); // NOI18N
        btnAnular.setText("Anular");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salirMarca.png"))); // NOI18N
        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel5Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAnular, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(81, Short.MAX_VALUE)));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnular)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir)
                                .addContainerGap(25, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane7)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(33, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 172,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(50, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBoletaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_radioBoletaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_radioBoletaActionPerformed

    private void btnBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarVentaActionPerformed
        buscarVenta();
    }// GEN-LAST:event_btnBuscarVentaActionPerformed

    private void btnBucarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBucarClienteActionPerformed
        buscarCliente();
    }// GEN-LAST:event_btnBucarClienteActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarProductoActionPerformed
        agregarProductoTabla();
    }// GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnQuitarProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuitarProductoActionPerformed
        quitarProductoTabla();
    }// GEN-LAST:event_btnQuitarProductoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed
        guardarVenta();
    }// GEN-LAST:event_btnGuardarActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAnularActionPerformed
        anularVenta();
    }// GEN-LAST:event_btnAnularActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }// GEN-LAST:event_btnSalirActionPerformed

    private void tablaVentaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tablaVentaMouseClicked
        seleccionarFilaTabla();
    }// GEN-LAST:event_tablaVentaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                jdVenta dialog = new jdVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnBucarCliente;
    private javax.swing.JButton btnBuscarVenta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitarProducto;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboTipoCliente;
    private com.toedter.calendar.JDateChooser dateVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane9;
    private javax.swing.JTextPane numVenta;
    private javax.swing.JRadioButton radioBoleta;
    private javax.swing.JRadioButton radioFactura;
    private javax.swing.JSpinner spinnerCantProd;
    private javax.swing.JTable tablaVenta;
    private javax.swing.JTextPane txtDescuento;
    private javax.swing.JTextPane txtDireccion;
    private javax.swing.JTextPane txtDni;
    private javax.swing.JTextPane txtIGV;
    private javax.swing.JTextPane txtNomCliente;
    private javax.swing.JTextPane txtNomProducto;
    private javax.swing.JTextPane txtSubtotal;
    // End of variables declaration//GEN-END:variables

    // ==================== MÉTODOS PERSONALIZADOS ====================

    private void buscarCliente() {
        String dniRuc = txtDni.getText().trim();

        if (dniRuc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI/RUC para buscar");
            return;
        }

        clsCliente cliente = clsClienteDao.buscarPorDniRuc(dniRuc);
        if (cliente != null) {
            txtNomCliente.setText(cliente.getNombre());
            txtDireccion.setText(cliente.getDireccion());
            // Seleccionar el tipo de cliente en el combo
            String tipo = cliente.getTipoCliente();
            for (int i = 0; i < comboTipoCliente.getItemCount(); i++) {
                if (comboTipoCliente.getItemAt(i).equals(tipo)) {
                    comboTipoCliente.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado");
            txtNomCliente.setText("");
            txtDireccion.setText("");
        }
    }

    private void buscarVenta() {
        String numeroVenta = numVenta.getText().trim();

        if (numeroVenta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de venta para buscar");
            return;
        }

        clsVenta venta = clsVentaDao.buscarPorNumero(numeroVenta);
        if (venta != null) {
            // Cargar datos de la venta encontrada
            txtDni.setText(venta.getClienteDniRuc());
            txtNomCliente.setText(venta.getClienteNombre());

            // Agregar a la tabla
            DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
            modelo.setRowCount(0);

            double precio = venta.getProductoPrecio();
            int cantidad = venta.getCantidad();
            double subtotal = venta.calcularSubtotal();

            modelo.addRow(new Object[] {
                    venta.getProductoCodigo(),
                    venta.getProductoNombre(),
                    String.format("%.2f", precio),
                    cantidad,
                    "0",
                    String.format("%.2f", precio),
                    String.format("%.2f", subtotal)
            });

            calcularTotales();
            JOptionPane.showMessageDialog(this, "Venta encontrada");
        } else {
            JOptionPane.showMessageDialog(this, "Venta no encontrada");
        }
    }

    private void agregarProductoTabla() {
        String nombreProducto = txtNomProducto.getText().trim();

        if (nombreProducto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre o código del producto");
            return;
        }

        // Buscar producto por código o nombre
        clsProducto producto = clsProductoDao.buscarPorCodigo(nombreProducto);

        // Si no lo encuentra por código, buscar en todos los productos por nombre
        if (producto == null) {
            clsProducto[] productos = clsProductoDao.obtener();
            for (int i = 0; i < clsProductoDao.getCantidad(); i++) {
                if (productos[i] != null
                        && productos[i].getNombre().toUpperCase().contains(nombreProducto.toUpperCase())) {
                    producto = productos[i];
                    break;
                }
            }
        }

        if (producto == null) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
            return;
        }

        // Obtener cantidad y descuento
        int cantidad = (Integer) spinnerCantProd.getValue();
        if (cantidad <= 0) {
            cantidad = 1;
        }

        double descuento = 0;
        try {
            String descuentoStr = txtDescuento.getText().trim();
            if (!descuentoStr.isEmpty()) {
                descuento = Double.parseDouble(descuentoStr);
            }
        } catch (NumberFormatException e) {
            descuento = 0;
        }

        double precio = producto.getPrecio();
        double nuevoPrecio = precio - (precio * descuento / 100);
        double subtotal = nuevoPrecio * cantidad;

        // Guardar datos del producto seleccionado
        codigoProductoSeleccionado = producto.getCodigo();
        precioProductoSeleccionado = precio;

        // Agregar a la tabla
        DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
        modelo.addRow(new Object[] {
                producto.getCodigo(),
                producto.getNombre(),
                String.format("%.2f", precio),
                cantidad,
                String.format("%.0f%%", descuento),
                String.format("%.2f", nuevoPrecio),
                String.format("%.2f", subtotal)
        });

        calcularTotales();
        limpiarProducto();
    }

    private void quitarProductoTabla() {
        int filaSeleccionada = tablaVenta.getSelectedRow();

        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para quitar");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
        modelo.removeRow(filaSeleccionada);

        calcularTotales();
    }

    private void calcularTotales() {
        DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
        double subtotalGeneral = 0;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String subtotalStr = modelo.getValueAt(i, 6).toString().replace(",", ".");
            subtotalGeneral += Double.parseDouble(subtotalStr);
        }

        double igv = subtotalGeneral * 0.18;
        double total = subtotalGeneral + igv;

        txtSubtotal.setText(String.format("%.2f", subtotalGeneral));
        txtIGV.setText(String.format("%.2f", igv));
        jTextPane9.setText(String.format("%.2f", total));
    }

    private void guardarVenta() {
        // Validar que haya cliente
        String dniRuc = txtDni.getText().trim();
        String nombreCliente = txtNomCliente.getText().trim();

        if (dniRuc.isEmpty() || nombreCliente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente");
            return;
        }

        // Validar que haya productos en la tabla
        DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Debe agregar al menos un producto");
            return;
        }

        // Obtener fecha
        LocalDate fecha = LocalDate.now();
        if (dateVenta.getDate() != null) {
            Date date = dateVenta.getDate();
            fecha = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        // Generar número de venta
        String numeroVentaGen = clsVentaDao.generarNumeroVenta();

        // Guardar cada producto como una venta separada (o se puede crear una
        // estructura más compleja)
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String codigoProd = modelo.getValueAt(i, 0).toString();
            String nombreProd = modelo.getValueAt(i, 1).toString();
            double precioProd = Double.parseDouble(modelo.getValueAt(i, 2).toString().replace(",", "."));
            int cantidadProd = Integer.parseInt(modelo.getValueAt(i, 3).toString());

            clsVenta venta = new clsVenta(
                    numeroVentaGen,
                    fecha,
                    dniRuc,
                    nombreCliente,
                    codigoProd,
                    nombreProd,
                    precioProd,
                    cantidadProd,
                    true);

            clsVentaDao.agregar(venta);
        }

        numVenta.setText(numeroVentaGen);
        JOptionPane.showMessageDialog(this, "Venta guardada correctamente\nNúmero: " + numeroVentaGen);
    }

    private void anularVenta() {
        String numeroVentaStr = numVenta.getText().trim();

        if (numeroVentaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay venta para anular. Busque una venta primero.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de anular la venta " + numeroVentaStr + "?",
                "Confirmar anulación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            if (clsVentaDao.anularVenta(numeroVentaStr)) {
                JOptionPane.showMessageDialog(this, "Venta anulada correctamente");
                limpiarTodo();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo anular la venta");
            }
        }
    }

    private void limpiarProducto() {
        txtNomProducto.setText("");
        spinnerCantProd.setValue(0);
        txtDescuento.setText("");
        codigoProductoSeleccionado = "";
        precioProductoSeleccionado = 0.0;
    }

    private void limpiarTodo() {
        // Limpiar campos de venta
        numVenta.setText("");
        dateVenta.setDate(null);

        // Limpiar campos de cliente
        txtDni.setText("");
        txtNomCliente.setText("");
        txtDireccion.setText("");
        comboTipoCliente.setSelectedIndex(0);
        radioBoleta.setSelected(false);
        radioFactura.setSelected(false);

        // Limpiar campos de producto
        limpiarProducto();

        // Limpiar tabla
        DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
        modelo.setRowCount(0);

        // Limpiar totales
        txtSubtotal.setText("");
        txtIGV.setText("");
        jTextPane9.setText("");
    }

    private void seleccionarFilaTabla() {
        int fila = tablaVenta.getSelectedRow();

        if (fila >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
            String codigo = modelo.getValueAt(fila, 0).toString();
            String nombre = modelo.getValueAt(fila, 1).toString();
            String cantidad = modelo.getValueAt(fila, 3).toString();

            txtNomProducto.setText(nombre);
            spinnerCantProd.setValue(Integer.parseInt(cantidad));
            codigoProductoSeleccionado = codigo;
        }
    }

    /**
     * Cargar las ventas existentes del DAO en la tabla
     */
    private void cargarVentasEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaVenta.getModel();
        modelo.setRowCount(0); // Limpiar tabla primero

        clsVenta[] ventas = clsVentaDao.obtener();
        int cantidad = clsVentaDao.getCantidad();

        for (int i = 0; i < cantidad; i++) {
            if (ventas[i] != null && ventas[i].isEstado()) {
                double precio = ventas[i].getProductoPrecio();
                int cantidadProd = ventas[i].getCantidad();
                double subtotal = ventas[i].calcularSubtotal();

                modelo.addRow(new Object[] {
                        ventas[i].getProductoCodigo(),
                        ventas[i].getProductoNombre(),
                        String.format("%.2f", precio),
                        cantidadProd,
                        "0%",
                        String.format("%.2f", precio),
                        String.format("%.2f", subtotal)
                });
            }
        }

        // Calcular totales después de cargar los datos
        if (modelo.getRowCount() > 0) {
            calcularTotales();
        }
    }
}
