/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package capa_presentacion;

/**
 *
 * @author mauricio
 */
public class jdManPeliculas extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(jdManPeliculas.class.getName());

    /**
     * Creates new form jdManPeliculas
     */
    public jdManPeliculas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        checkActivo = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDirector = new javax.swing.JTextField();
        txtActor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBuscarDirector = new javax.swing.JButton();
        btnBuscarActor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("ID");

        tablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {

                }));
        tablaPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPeliculasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPeliculas);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel4.setText("Mantenimineto Peliculas");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("Titulo");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Assets/agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        checkActivo.setText("Activo");

        jLabel2.setText("Genero");

        jLabel3.setText("Director");

        jLabel6.setText("Actor");

        btnBuscarDirector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Assets/buscar2.png"))); // NOI18N
        btnBuscarDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDirectorActionPerformed(evt);
            }
        });

        btnBuscarActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Assets/buscar2.png"))); // NOI18N
        btnBuscarActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel2)
                                                                .addComponent(jLabel1)
                                                                .addComponent(btnEliminar,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(btnModificar,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 190,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(txtTitulo)
                                                                .addComponent(comboTipo, 0,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel6)
                                                                .addComponent(jLabel5)
                                                                .addComponent(txtId)
                                                                .addComponent(btnAgregar,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(checkActivo)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(txtDirector,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                147, Short.MAX_VALUE)
                                                                        .addComponent(txtActor,
                                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnBuscarActor)
                                                                        .addComponent(btnBuscarDirector))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80,
                                                        Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnBuscarDirector)
                                                        .addComponent(txtDirector,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtActor, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnBuscarActor))
                                                .addGap(18, 18, 18)
                                                .addComponent(checkActivo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16,
                                                        Short.MAX_VALUE)
                                                .addComponent(btnAgregar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnModificar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnEliminar)
                                                .addGap(49, 49, 49)))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarDirectorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarDirectorActionPerformed
        aniadirDirector dialog = new aniadirDirector((java.awt.Frame) getParent(), true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        String seleccion = dialog.getSeleccion();
        if (seleccion != null && !seleccion.isEmpty()) {
            txtDirector.setText(seleccion);
        }
    }// GEN-LAST:event_btnBuscarDirectorActionPerformed

    private void btnBuscarActorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActorActionPerformed
        aniadirActor dialog = new aniadirActor((java.awt.Frame) getParent(), true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        String seleccion = dialog.getSeleccion();
        if (seleccion != null && !seleccion.isEmpty()) {
            String actual = txtActor.getText();
            if (actual.isEmpty()) {
                txtActor.setText(seleccion);
            } else {
                txtActor.setText(actual + ", " + seleccion);
            }
        }
    }// GEN-LAST:event_btnBuscarActorActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarActionPerformed
        agregarPelicula();
    }// GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnModificarActionPerformed
        modificarPelicula();
    }// GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarActionPerformed
        eliminarPelicula();
    }// GEN-LAST:event_btnEliminarActionPerformed

    private void tablaPeliculasMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tablaPeliculasMouseClicked
        cargarDesdeTabla();
    }// GEN-LAST:event_tablaPeliculasMouseClicked

    private void listado() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Titulo");
        modelo.addColumn("Genero");
        modelo.addColumn("Director");
        modelo.addColumn("Actor");
        java.util.ArrayList<capa_logica.Pelicula> datos = capa_datos.PeliculaDAO.obtener();
        for (capa_logica.Pelicula p : datos) {
            modelo.addRow(new Object[] { p.getId(), p.getTitulo(), p.getGenero(), p.getDirector(), p.getActor() });
        }
        tablaPeliculas.setModel(modelo);
    }

    private void limpiar() {
        txtId.setText("");
        txtTitulo.setText("");
        comboTipo.setSelectedIndex(0);
        txtDirector.setText("");
        txtActor.setText("");
    }

    private void cargarDesdeTabla() {
        int fila = tablaPeliculas.getSelectedRow();
        if (fila >= 0) {
            int id = Integer.parseInt(tablaPeliculas.getValueAt(fila, 0).toString());
            java.util.ArrayList<capa_logica.Pelicula> datos = capa_datos.PeliculaDAO.obtener();
            for (capa_logica.Pelicula p : datos) {
                if (p.getId() == id) {
                    txtId.setText(String.valueOf(p.getId()));
                    txtTitulo.setText(p.getTitulo());
                    comboTipo.setSelectedItem(p.getGenero());
                    txtDirector.setText(p.getDirector());
                    txtActor.setText(p.getActor());
                    break;
                }
            }
        }
    }

    private void agregarPelicula() {
        if (txtTitulo.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete el titulo");
            return;
        }
        int id = capa_datos.PeliculaDAO.obtener().size() + 1;
        capa_logica.Pelicula p = new capa_logica.Pelicula(
                id,
                txtTitulo.getText(),
                comboTipo.getSelectedItem().toString(),
                txtDirector.getText(),
                txtActor.getText(),
                new java.util.Date(),
                0);
        capa_datos.PeliculaDAO.agrega(p);
        capa_datos.PeliculaDAO.grabar();
        javax.swing.JOptionPane.showMessageDialog(this, "Pelicula agregada");
        listado();
        limpiar();
    }

    private void modificarPelicula() {
        if (txtId.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una pelicula");
            return;
        }
        int id = Integer.parseInt(txtId.getText());
        java.util.ArrayList<capa_logica.Pelicula> datos = capa_datos.PeliculaDAO.obtener();
        for (int i = 0; i < datos.size(); i++) {
            if (datos.get(i).getId() == id) {
                capa_logica.Pelicula p = new capa_logica.Pelicula(
                        id,
                        txtTitulo.getText(),
                        comboTipo.getSelectedItem().toString(),
                        txtDirector.getText(),
                        txtActor.getText(),
                        datos.get(i).getFechaEstreno(),
                        datos.get(i).getPresupuesto());
                datos.set(i, p);
                capa_datos.PeliculaDAO.grabar();
                javax.swing.JOptionPane.showMessageDialog(this, "Pelicula modificada");
                listado();
                limpiar();
                break;
            }
        }
    }

    private void eliminarPelicula() {
        if (txtId.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una pelicula");
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "¿Eliminar pelicula?");
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(txtId.getText());
            java.util.ArrayList<capa_logica.Pelicula> datos = capa_datos.PeliculaDAO.obtener();
            for (int i = 0; i < datos.size(); i++) {
                if (datos.get(i).getId() == id) {
                    datos.remove(i);
                    capa_datos.PeliculaDAO.grabar();
                    javax.swing.JOptionPane.showMessageDialog(this, "Pelicula eliminada");
                    listado();
                    limpiar();
                    break;
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                jdManPeliculas dialog = new jdManPeliculas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarActor;
    private javax.swing.JButton btnBuscarDirector;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox checkActivo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPeliculas;
    private javax.swing.JTextField txtActor;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
