/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package capa_presentacion;

/**
 *
 * @author mauricio
 */
public class jdManusuarios extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(jdManusuarios.class.getName());

    /**
     * Creates new form jdManUsuario
     */
    public jdManusuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableUsr = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        comboTipo = new javax.swing.JComboBox<>();
        checkActivo = new javax.swing.JCheckBox();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Tipo");

        jLabel3.setText("Contraseña");

        jtableUsr.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {

                }));
        jtableUsr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableUsrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableUsr);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel4.setText("Mantenimineto Usuarios");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Assets/agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Administrador", "Gerente", "Empleado", "Usuario" }));

        checkActivo.setText("Activo");

        jLabel5.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel1)
                                                        .addComponent(txtContra)
                                                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                146, Short.MAX_VALUE)
                                                        .addComponent(btnModificar,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtNombre)
                                                        .addComponent(comboTipo, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(checkActivo)
                                                        .addComponent(jLabel5)
                                                        .addComponent(txtId))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37,
                                                        Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22,
                                                        Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(checkActivo)
                                                .addGap(33, 33, 33)
                                                .addComponent(btnAgregar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnModificar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnEliminar)))
                                .addContainerGap(54, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarActionPerformed
        agregarUsuario();
    }// GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnModificarActionPerformed
        modificarUsuario();
    }// GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarActionPerformed
        eliminarUsuario();
    }// GEN-LAST:event_btnEliminarActionPerformed

    private void jtableUsrMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jtableUsrMouseClicked
        cargarDesdeTabla();
    }// GEN-LAST:event_jtableUsrMouseClicked

    private void listado() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Tipo");
        modelo.addColumn("Estado");
        java.util.ArrayList<capa_logica.Usuario> datos = capa_datos.UsuarioDAO.obtener();
        for (capa_logica.Usuario u : datos) {
            String estado = u.isEstado() ? "Activo" : "Inactivo";
            modelo.addRow(new Object[] { u.getId(), u.getNombre(), u.getTipo(), estado });
        }
        jtableUsr.setModel(modelo);
    }

    private void limpiar() {
        txtId.setText("");
        txtNombre.setText("");
        txtContra.setText("");
        comboTipo.setSelectedIndex(0);
        checkActivo.setSelected(false);
    }

    private void cargarDesdeTabla() {
        int fila = jtableUsr.getSelectedRow();
        if (fila >= 0) {
            int id = Integer.parseInt(jtableUsr.getValueAt(fila, 0).toString());
            java.util.ArrayList<capa_logica.Usuario> datos = capa_datos.UsuarioDAO.obtener();
            for (capa_logica.Usuario u : datos) {
                if (u.getId() == id) {
                    txtId.setText(String.valueOf(u.getId()));
                    txtNombre.setText(u.getNombre());
                    txtContra.setText(u.getClave());
                    comboTipo.setSelectedItem(u.getTipo());
                    checkActivo.setSelected(u.isEstado());
                    break;
                }
            }
        }
    }

    private void agregarUsuario() {
        if (txtNombre.getText().isEmpty() || txtContra.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }
        int id = capa_datos.UsuarioDAO.obtener().size() + 1;
        capa_logica.Usuario u = new capa_logica.Usuario(
                id,
                txtContra.getText(),
                txtNombre.getText(),
                comboTipo.getSelectedItem().toString(),
                checkActivo.isSelected());
        capa_datos.UsuarioDAO.agrega(u);
        capa_datos.UsuarioDAO.grabar();
        javax.swing.JOptionPane.showMessageDialog(this, "Usuario agregado");
        listado();
        limpiar();
    }

    private void modificarUsuario() {
        if (txtId.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un usuario");
            return;
        }
        int id = Integer.parseInt(txtId.getText());
        java.util.ArrayList<capa_logica.Usuario> datos = capa_datos.UsuarioDAO.obtener();
        for (int i = 0; i < datos.size(); i++) {
            if (datos.get(i).getId() == id) {
                capa_logica.Usuario u = new capa_logica.Usuario(
                        id,
                        txtContra.getText(),
                        txtNombre.getText(),
                        comboTipo.getSelectedItem().toString(),
                        checkActivo.isSelected());
                datos.set(i, u);
                capa_datos.UsuarioDAO.grabar();
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario modificado");
                listado();
                limpiar();
                break;
            }
        }
    }

    private void eliminarUsuario() {
        if (txtId.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un usuario");
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "¿Eliminar usuario?");
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(txtId.getText());
            java.util.ArrayList<capa_logica.Usuario> datos = capa_datos.UsuarioDAO.obtener();
            for (int i = 0; i < datos.size(); i++) {
                if (datos.get(i).getId() == id) {
                    datos.remove(i);
                    capa_datos.UsuarioDAO.grabar();
                    javax.swing.JOptionPane.showMessageDialog(this, "Usuario eliminado");
                    listado();
                    limpiar();
                    break;
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                jdManusuarios dialog = new jdManusuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox checkActivo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableUsr;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
