/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package capa_presentacion;

/**
 *
 * @author mauricio
 */
public class Reportes extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reportes.class.getName());
    private String tipoReporte = "usuarios";

    /** Creates new form Reportes */
    public Reportes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarBusqueda();
        listarUsuarios();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnUSr = new javax.swing.JButton();
        btnGeneros = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();
        btnActor = new javax.swing.JButton();
        btnUsr = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {

                }));
        jScrollPane1.setViewportView(tabla);

        btnUSr.setText("Usuarios");
        btnUSr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUSrActionPerformed(evt);
            }
        });

        btnGeneros.setText("Generos");
        btnGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerosActionPerformed(evt);
            }
        });

        btnPeliculas.setText("Peliculas");
        btnPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculasActionPerformed(evt);
            }
        });

        btnActor.setText("Actores");
        btnActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActorActionPerformed(evt);
            }
        });

        btnUsr.setText("Usuarios");
        btnUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBuscar)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(btnUSr, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnGeneros)
                                                        .addComponent(btnPeliculas)
                                                        .addComponent(btnUsr, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnActor, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(65, 65, 65)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(43, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnUSr, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnActor, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsrActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUsrActionPerformed
        tipoReporte = "directores";
        listarDirectores();
    }// GEN-LAST:event_btnUsrActionPerformed

    private void btnActorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnActorActionPerformed
        tipoReporte = "actores";
        listarActores();
    }// GEN-LAST:event_btnActorActionPerformed

    private void btnPeliculasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPeliculasActionPerformed
        tipoReporte = "peliculas";
        listarPeliculas();
    }// GEN-LAST:event_btnPeliculasActionPerformed

    private void btnGenerosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGenerosActionPerformed
        tipoReporte = "generos";
        listarGeneros();
    }// GEN-LAST:event_btnGenerosActionPerformed

    private void btnUSrActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUSrActionPerformed
        tipoReporte = "usuarios";
        listarUsuarios();
    }// GEN-LAST:event_btnUSrActionPerformed

    private void listarUsuarios() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Tipo");
        modelo.addColumn("Estado");
        java.util.ArrayList<capa_logica.Usuario> datos = capa_datos.UsuarioDAO.obtener();
        for (capa_logica.Usuario u : datos) {
            String estado = u.isEstado() ? "Activo" : "Inactivo";
            modelo.addRow(new Object[] { u.getId(), u.getNombre(), u.getTipo(), estado });
        }
        tabla.setModel(modelo);
    }

    private void listarActores() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Nacionalidad");
        java.util.ArrayList<capa_logica.Actor> datos = capa_datos.ActorDAO.obtener();
        for (capa_logica.Actor a : datos) {
            modelo.addRow(new Object[] { a.getId(), a.getNombre(), a.getPais() });
        }
        tabla.setModel(modelo);
    }

    private void listarDirectores() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Nacionalidad");
        java.util.ArrayList<capa_logica.Director> datos = capa_datos.DirectorDAO.obtener();
        for (capa_logica.Director d : datos) {
            modelo.addRow(new Object[] { d.getId(), d.getNombre(), d.getPais() });
        }
        tabla.setModel(modelo);
    }

    private void listarGeneros() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Descripcion");
        java.util.ArrayList<capa_logica.Genero> datos = capa_datos.GeneroDAO.obtener();
        for (capa_logica.Genero g : datos) {
            modelo.addRow(new Object[] { g.getId(), g.getDescripcion() });
        }
        tabla.setModel(modelo);
    }

    private void listarPeliculas() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Titulo");
        modelo.addColumn("Genero");
        modelo.addColumn("Director");
        modelo.addColumn("Actor");
        java.util.ArrayList<capa_logica.Pelicula> datos = capa_datos.PeliculaDAO.obtener();
        for (capa_logica.Pelicula p : datos) {
            modelo.addRow(new Object[] { p.getId(), p.getTitulo(), p.getGenero(), p.getDirector(), p.getActor() });
        }
        tabla.setModel(modelo);
    }

    private void configurarBusqueda() {
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtrar(txtBuscar.getText());
            }
        });
    }

    private void filtrar(String texto) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabla.getModel();
        javax.swing.RowFilter<Object, Object> rf = null;
        try {
            rf = javax.swing.RowFilter.regexFilter("(?i)" + texto);
        } catch (java.util.regex.PatternSyntaxException e) {
            return;
        }
        javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(
                modelo);
        sorter.setRowFilter(rf);
        tabla.setRowSorter(sorter);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Reportes dialog = new Reportes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActor;
    private javax.swing.JButton btnGeneros;
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JButton btnUSr;
    private javax.swing.JButton btnUsr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
